FROM eclipse-temurin:21-jdk   #taking base image from dockerhub. eclipse temurin publish kore base image dockerhub e

COPY hello.java /app #ekhan theke source code copy koro code niye then app er bhitore rakho

WORKDIR /app #jehetu app e hocche app e rakhteche tahole eta hocche working directory ei directory te run korbe

RUN javac hello.java #run korbe java code tar age compile kore nibe javac mane java compiler

CMD ["java", "hello"] #normal python e jemon pythonfile.py emn ekta jinish





