FROM python:3.9-slim  
#take base image from dockerhub, slim means ekhane just necessary python chalanor jonno file thake unnecessary thakena, normal ta te sob library image tools bla bla thake

WORKDIR /app

COPY . /app 
#. means current folder, current folder e ekhane ja ja ase sob app e niye rakha hoilo

CMD ["python", "app.py"] 



